name: helping_hands_app
description: A cross-platform mobile app connecting helpers with helpees for household tasks in Sri Lanka.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Multilingual Support
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  
  # Navigation
  go_router: ^14.2.7
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  fl_chart: ^0.68.0
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.4.3+1
  
  # Database & Backend
  supabase_flutter: ^2.5.6
  
  # Authentication
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  
  # Storage
  shared_preferences: ^2.2.3
  path_provider: ^2.1.1
  
  # Security & Encryption
  crypto: ^3.0.3
  
  # Location Services (No Google APIs)
  geolocator: ^12.0.0
  
  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  
  # File Handling
  file_picker: ^8.0.7
  
  # WebRTC Calling (FREE Alternative) & Permissions
  # flutter_webrtc: ^0.9.48+hotfix.1 # Temporarily disabled due to compilation issues
  permission_handler: ^11.0.1
  
  # Notifications
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.2
  
  # Utils
  uuid: ^4.4.0
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Manjari
  #     fonts:
  #       - asset: assets/fonts/Manjari-Regular.ttf
  #       - asset: assets/fonts/Manjari-Bold.ttf
  #         weight: 700 